# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42e4bdcb9bdcbe9d613456e34e86045d481aad6f417662fc1e3dfc91b182fee1ef1db965fb686cbb94caa7a8929caffa915ad4d9339b19e60c229f93bdd98d9c

test:
  secret_key_base: 79c8344c2474e0ce4e4fb470434185b6aed8b6e76a512194f1cdcf69ba9c24efc776b7a293b0a2a007c869e59b54e468ba5d348f3dbf4e2709ea3edfa85f8b20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
